log_level: "INFO"
log_file: "logs/defyvision.log"

service:
  login_enabled: true
  username: "DEFYMOTION"
  password: "defy2026"

camera:
  retry_interval_s: 3.0 # segundos de espera entre cada intento de reconexión
