scanner_1:
  username: root
  password: defy2026
  open_timeout_s: 10
  focus: 26
  exposure: -10
  white_balance: 4500
  gain: 0
  brightness: 188
  contrast: 140
  saturation: 50
  sharpness: 160
  gamma: 110
  backlight_compensation: 0
  autofocus: false
  auto_exposure: false
  auto_white_balance: true
scanner_2:
  username: root
  password: defy2026
  open_timeout_s: 10
  focus: 38
  exposure: -9
  white_balance: 4500
  gain: 0
  brightness: 188
  contrast: 174
  saturation: 50
  sharpness: 160
  gamma: 110
  backlight_compensation: 0
  autofocus: false
  auto_exposure: false
  auto_white_balance: true
