scanner_1:
  autofocus: true
  focus: 100
  auto_exposure: true
  exposure: -7
  auto_white_balance: true
  white_balance: 4500
  gain: 0
  brightness: 128
  contrast: 140
  saturation: 50
  sharpness: 160
  gamma: 110
  backlight_compensation: 0

scanner_2:
  autofocus: true
  focus: 100
  auto_exposure: true
  exposure: -7
  auto_white_balance: true
  white_balance: 4500
  gain: 0
  brightness: 128
  contrast: 140
  saturation: 50
  sharpness: 160
  gamma: 110
  backlight_compensation: 0
