[GPI1]
; 操作名称
aliasName = GPI1
; 1 则设置当前为输出，0 则为输入
isOutput = 0          
; 1 则说明此地址为MMIO 地址，0 则标识为PIO地址,默认为0 PIO.
isMemoryMap = 0
 ; 端口操作地址，
portOrPhysAddr = 0xA00
; 端口操作位 起始位0
portOrPhysBit = 0
; 默认电平状态，1 高,0 低，2 为不变，默认为不变
default = 1
[GPI2]
aliasName = GPI2
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA00
portOrPhysBit = 2
default = 1
[GPI3]
aliasName = GPI3  
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA00
portOrPhysBit = 7
default = 1
[GPI4]
aliasName = GPI4   
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA02
portOrPhysBit = 0
default = 1
[GPI5]
aliasName = GPI5   
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA00
portOrPhysBit = 4
default = 1
[GPI6]
aliasName = GPI6   
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA03
portOrPhysBit = 4
default = 1
[GPI7]
aliasName = GPI7   
isOutput = 0          
isMemoryMap = 0
portOrPhysAddr = 0xA04
portOrPhysBit = 3
default = 1

[GPO1]
aliasName = GPO1
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA03
portOrPhysBit = 1
default = 0
[GPO2]
aliasName = GPO2
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA05
portOrPhysBit = 5
default = 1
[GPO3]
aliasName = GPO3
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA00
portOrPhysBit = 1
default = 1
[GPO4]
aliasName = GPO4
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA03
portOrPhysBit = 6
default = 1
[GPO5]
aliasName = GPO5
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA04
portOrPhysBit = 5
default = 1
[GPO6]
aliasName = GPO6
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA04
portOrPhysBit = 4
default = 1
[GPO7]
aliasName = GPO7
isOutput = 1          
isMemoryMap = 0
portOrPhysAddr = 0xA03
portOrPhysBit = 0
default = 1
[baseconfig]

;公司名称
corporateName =深圳市博锶腾科技有限公司
;校验值
verification =a47eafdbc8ddfe37de0ed71d5dce5c9d
;输入端口轮询时间间隔,单位毫秒
timeInterval=500
indexPort=0x2e
indexData=0x2f
